/* 1- TABELA SITUACAO */
CREATE TABLE SITUACAO(
IDSITUACAO INT  AUTO_INCREMENT ,
Situacao VARCHAR(10) NOT NULL,

CONSTRAINT PK_Situacao PRIMARY KEY (IDSITUACAO)
);


/*2 - TABELA SOCIO LIGADA A TABELA SITUACAO  PELA FK Id_Situacao*/
CREATE TABLE SOCIO (
IDSOCIO INT AUTO_INCREMENT ,
Nome VARCHAR(64) NOT NULL,
CPF VARCHAR(11) NOT NULL,
Email VARCHAR(64) NOT NULL,
Id_Situacao INT ,

CONSTRAINT PK_Socio PRIMARY KEY (IDSOCIO),
CONSTRAINT FK_SOCIO_REF_SITUACAO FOREIGN KEY (Id_Situacao)
REFERENCES SITUACAO (Id_Situacao)
);


/* 3-  TABELA MARCA */
CREATE TABLE MARCA (
IDMARCA INT AUTO_INCREMENT ,
Marca VARCHAR (128) NOT NULL,

CONSTRAINT PK_Marca PRIMARY KEY (IDMARCA)
);


/* 4-  TABELA CARRO LIGADA A TABELA SOCIO E MARCA PELAS FK 
Id_Socio e Id_Marca respectivamente.
*/

CREATE TABLE CARRO(
IDCARRO INT AUTO_INCREMENT ,
Modelo VARCHAR(64)NOT NULL,
Cor VARCHAR (64)NOT NULL,
Placa VARCHAR(10)NOT NULL,
Id_Socio INT ,
Id_Marca INT ,

CONSTRAINT PK_Carro PRIMARY KEY (IDCARRO),
CONSTRAINT FK_CARRO_REF_SOCIO FOREIGN KEY (Id_Socio)
REFERENCES SOCIO (Id_Socio),
CONSTRAINT FK_CARRO_REF_MARCA FOREIGN KEY (Id_Marca)
REFERENCES MARCA(Id_Marca)
);





